import React, { useRef, useState, useEffect } from 'react';
import { View, StyleSheet } from 'react-native';
import LottieView from 'lottie-react-native';
import { Text } from '@ui-kitten/components';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function OnBoardingSlide3({ isActive }) {
    const animationRef = useRef(null);
    const [isMounted, setIsMounted] = useState(false);

    useEffect(() => {
        if (isActive) {
            try {
                animationRef.current?.reset();
                animationRef.current?.play(40, 200); // Safe but reversed frame order (optional fix below)
            } catch (e) {
                console.warn('⚠️ Animation play failed:', e);
            }
        }

        if (!isActive && isMounted) {
            try {
                animationRef.current?.reset();
            } catch (e) {
                console.warn('⚠️ Animation reset failed:', e);
            }
        }
    }, [isActive, isMounted]);

    return (
        <SafeAreaView style={{ flex: 1, backgroundColor: '#fff' }} edges={['top', 'bottom']}>
            <View style={styles.slide}>
                <LottieView
                    ref={(ref) => {
                        animationRef.current = ref;
                        if (ref && !isMounted) setIsMounted(true);
                    }}
                    source={require('../assets/brainStromingAnimation.json')}
                    loop={true}
                    autoPlay={false}
                    style={{ width: 200, height: 200, marginTop: '20%', alignSelf: 'center' }}
                    onError={(error) => console.error('❌ Lottie failed to load:', error)}
                />
                <Text category="h4" style={styles.title}>Train Your Brain</Text>
                <Text style={styles.text}>
                    Take daily AI-generated quizzes and microlearn your course.
                </Text>
                <Text style={styles.disclaimer}>
                    Disclaimer: All quizzes are generated by AI and may contain inaccuracies.
                </Text>
            </View>
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    slide: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 30,
    },
    title: {
        marginBottom: 10,
        textAlign: 'center',
    },
    text: {
        textAlign: 'center',
        paddingHorizontal: 10,
    },
    disclaimer: {
        marginTop: 40,
        fontSize: 12,
        textAlign: 'center',
        color: 'gray',
        paddingHorizontal: 20,
    },
});