// backgroundtask.js
import * as TaskManager from 'expo-task-manager';
import * as Notifications from 'expo-notifications';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { generateQuizFromText } from './generateQuiz';
import { parseQuizJson } from './parseQuiz';

export const TASK_NAME = 'reschedule-daily-reminder-task';

export const runBackgroundQuizGeneration = async () => {
    __DEV__ && console.log('🧪 Triggering background task manually...');
    try {
        const settingsStr = await AsyncStorage.getItem('quiz-settings');
        if (!settingsStr) {
            __DEV__ && console.log('⚠️ No settings found');
            return;
        }

        let settings;
        try {
            settings = JSON.parse(settingsStr);
        } catch (e) {
            __DEV__ && console.error('❌ Failed to parse quiz-settings:', e);
            return;
        }

        if (!settings.reminderEnabled) {
            __DEV__ && console.log('🔕 Reminder is disabled in settings');
            return;
        }

        const stored = await AsyncStorage.getItem('study-materials');
        const materials = stored ? JSON.parse(stored) : [];

        if (!Array.isArray(materials) || materials.length === 0) {
            __DEV__ && console.log('📂 No study materials for quiz generation.');
            return;
        }

        const randomIndex = Math.floor(Math.random() * materials.length);
        const selectedMaterial = materials[randomIndex];

        if (!selectedMaterial?.text) {
            __DEV__ && console.log('⚠️ Selected material has no text. Skipping...');
            return;
        }

        const todayStr = new Date().toISOString().split('T')[0];
        const quizKey = `quizAG-${todayStr}`;
        const existing = await AsyncStorage.getItem(quizKey);
        const userStatus = await AsyncStorage.getItem('user-tier') || 'normal';

        if (!existing) {
            let generatedQuiz;
            try {
                generatedQuiz = await generateQuizFromText(
                    selectedMaterial.text,
                    {
                        numberOfQuestions: settings.quizLength || 5,
                        difficulty: settings.difficulty || 'easy',
                        generationMode: 'Auto',
                    },
                    null,
                    userStatus
                );
            } catch (e) {
                __DEV__ && console.error('❌ Quiz generation failed:', e);
                return;
            }

            let parsedQuiz;
            try {
                parsedQuiz = parseQuizJson(generatedQuiz);
            } catch (e) {
                __DEV__ && console.error('❌ Failed to parse generated quiz:', e);
                return;
            }

            await AsyncStorage.setItem('autoQuizShown', 'false');
            await AsyncStorage.setItem(quizKey, JSON.stringify(parsedQuiz));
            __DEV__ && console.log(`✅ Quiz autogenerated and saved as ${quizKey}`);
        } else {
            __DEV__ && console.log(`📦 Quiz already exists for today (${quizKey})`);
        }

        let reminderTime;
        try {
            reminderTime = new Date(settings.reminderTime);
            if (isNaN(reminderTime.getTime())) throw new Error('Invalid Date');
        } catch (e) {
            __DEV__ && console.error('❌ Invalid reminder time:', e);
            return;
        }

        const nextReminder = new Date();
        nextReminder.setHours(reminderTime.getHours(), reminderTime.getMinutes(), 0, 0);
        if (nextReminder <= new Date()) {
            nextReminder.setDate(nextReminder.getDate() + 1);
        }

        try {
            await Notifications.cancelAllScheduledNotificationsAsync();
            await Notifications.scheduleNotificationAsync({
                content: {
                    title: 'Time to Study 🧠',
                    body: 'Your daily ThinkB quiz is ready!',
                    sound: true,
                },
                trigger: {
                    type: Notifications.SchedulableTriggerInputTypes.DATE,
                    date: nextReminder,
                },
            });
            __DEV__ && console.log('🔁 Notification rescheduled for:', nextReminder.toString());
        } catch (e) {
            __DEV__ && console.error('❌ Failed to schedule notification:', e);
        }

    } catch (err) {
        __DEV__ && console.error('❌ Error in background quiz generation:', err);
    }
};